### ISSUE TITLE
Scroll on Mobile

### ISSUE THREAD

**Issue by IslamicProgrammer** [qqww08/react-dynamic-bottom-sheet#1]
Cannot read properties of null (reading 'scrollTop') 

Cannot read properties of null (reading 'scrollTop')
TypeError: Cannot read properties of null (reading 'scrollTop')
    at onTouchStart (http://localhost:3000/static/js/bundle.js:231764:21)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:165101:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:165145:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:165202:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:165216:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:169360:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:169386:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:169397:9)
    at dispatchEventsForPlugins (http://localhost:3000/static/js/bundle.js:169406:7)
    at

**Comment by qqww08** [comment]
@IslamicProgrammer  Thank you for reporting. Please use version [2.0.2](https://github.com/qqww08/react-dynamic-bottom-sheet/releases/tag/v2.0.2)
